BASEDIR=../..
#MODULES=
MAIN_MODULE=test
C_FILES=stub_test

# This test relies on the upstream behaviour of -custom
export OCAML_CUSTOM_EMBED=n

include $(BASEDIR)/makefiles/Makefile.one
include $(BASEDIR)/makefiles/Makefile.common
